# Form implementation generated from reading ui file 'C:\Users\User\helloworld\build\helloworld\android\gradle\app\src\main\assets\Mirai-Ko-Girls-UI.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1211, 777)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: #000000;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #000000; \n"
"    border: 1px solid #FFFFFF;\n"
"\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFFFFF\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ControlCenter = QtWidgets.QFrame(parent=self.centralwidget)
        self.ControlCenter.setGeometry(QtCore.QRect(420, 0, 371, 761))
        self.ControlCenter.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    background: transparent;\n"
"}")
        self.ControlCenter.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ControlCenter.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ControlCenter.setObjectName("ControlCenter")
        self.Logo = QtWidgets.QLabel(parent=self.ControlCenter)
        self.Logo.setGeometry(QtCore.QRect(50, 0, 261, 91))
        self.Logo.setWhatsThis("")
        self.Logo.setText("")
        self.Logo.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.Logo.setPixmap(QtGui.QPixmap("C:\\Users\\User\\helloworld\\build\\helloworld\\android\\gradle\\app\\src\\main\\assets\\assets/labels/logolabel.png"))
        self.Logo.setObjectName("Logo")
        self.Ver = QtWidgets.QLabel(parent=self.ControlCenter)
        self.Ver.setGeometry(QtCore.QRect(100, 90, 181, 31))
        self.Ver.setBaseSize(QtCore.QSize(2, 2))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(16)
        self.Ver.setFont(font)
        self.Ver.setObjectName("Ver")
        self.HLogo = QtWidgets.QLabel(parent=self.ControlCenter)
        self.HLogo.setGeometry(QtCore.QRect(80, 130, 211, 131))
        self.HLogo.setWhatsThis("")
        self.HLogo.setText("")
        self.HLogo.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.HLogo.setPixmap(QtGui.QPixmap("C:\\Users\\User\\helloworld\\build\\helloworld\\android\\gradle\\app\\src\\main\\assets\\assets/labels/hana logo.png"))
        self.HLogo.setScaledContents(True)
        self.HLogo.setWordWrap(True)
        self.HLogo.setOpenExternalLinks(False)
        self.HLogo.setObjectName("HLogo")
        self.HVer = QtWidgets.QLabel(parent=self.ControlCenter)
        self.HVer.setGeometry(QtCore.QRect(110, 260, 151, 31))
        self.HVer.setBaseSize(QtCore.QSize(2, 2))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(16)
        self.HVer.setFont(font)
        self.HVer.setObjectName("HVer")
        self.HVer_2 = QtWidgets.QLabel(parent=self.ControlCenter)
        self.HVer_2.setGeometry(QtCore.QRect(80, 300, 211, 131))
        self.HVer_2.setWhatsThis("")
        self.HVer_2.setLineWidth(0)
        self.HVer_2.setText("")
        self.HVer_2.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.HVer_2.setPixmap(QtGui.QPixmap("C:\\Users\\User\\helloworld\\build\\helloworld\\android\\gradle\\app\\src\\main\\assets\\assets/labels/hana2 logo.png"))
        self.HVer_2.setScaledContents(True)
        self.HVer_2.setWordWrap(True)
        self.HVer_2.setOpenExternalLinks(False)
        self.HVer_2.setObjectName("HVer_2")
        self.MVer = QtWidgets.QLabel(parent=self.ControlCenter)
        self.MVer.setGeometry(QtCore.QRect(110, 430, 161, 31))
        self.MVer.setBaseSize(QtCore.QSize(2, 2))
        font = QtGui.QFont()
        font.setFamily("Ebrima")
        font.setPointSize(16)
        self.MVer.setFont(font)
        self.MVer.setObjectName("MVer")
        self.GlobalChat = QtWidgets.QLineEdit(parent=self.ControlCenter)
        self.GlobalChat.setGeometry(QtCore.QRect(0, 740, 371, 21))
        self.GlobalChat.setStyleSheet("QLineEdit {\n"
"    background-color: #000000;\n"
"    border: 1px solid #1a1a1a;\n"
"    color: #ffffff;\n"
"    font-family: \'Consolas\', \'Monospace\';\n"
"    font-size: 10pt;\n"
"}")
        self.GlobalChat.setObjectName("GlobalChat")
        self.UploadBtn = QtWidgets.QPushButton(parent=self.ControlCenter)
        self.UploadBtn.setGeometry(QtCore.QRect(40, 680, 291, 41))
        self.UploadBtn.setObjectName("UploadBtn")
        self.ImagePreview = QtWidgets.QLabel(parent=self.ControlCenter)
        self.ImagePreview.setGeometry(QtCore.QRect(40, 500, 291, 151))
        self.ImagePreview.setStyleSheet("QLabel\n"
"border-color: rgb(255, 255, 255);")
        self.ImagePreview.setText("")
        self.ImagePreview.setObjectName("ImagePreview")
        self.Meibi = QtWidgets.QFrame(parent=self.centralwidget)
        self.Meibi.setGeometry(QtCore.QRect(800, 0, 411, 761))
        self.Meibi.setStyleSheet("")
        self.Meibi.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Meibi.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Meibi.setObjectName("Meibi")
        self.Face_2 = QtWidgets.QLabel(parent=self.Meibi)
        self.Face_2.setGeometry(QtCore.QRect(0, 50, 381, 291))
        self.Face_2.setText("")
        self.Face_2.setPixmap(QtGui.QPixmap("C:\\Users\\User\\helloworld\\build\\helloworld\\android\\gradle\\app\\src\\main\\assets\\assets/hana2_faces/5.png"))
        self.Face_2.setScaledContents(True)
        self.Face_2.setWordWrap(False)
        self.Face_2.setObjectName("Face_2")
        self.Label_2 = QtWidgets.QLabel(parent=self.Meibi)
        self.Label_2.setGeometry(QtCore.QRect(0, 10, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(24)
        font.setBold(True)
        self.Label_2.setFont(font)
        self.Label_2.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    padding: 5px;\n"
"    background-color: #000000;\n"
"}")
        self.Label_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Label_2.setLineWidth(2)
        self.Label_2.setMidLineWidth(1)
        self.Label_2.setObjectName("Label_2")
        self.meibi_log = QtWidgets.QTextEdit(parent=self.Meibi)
        self.meibi_log.setGeometry(QtCore.QRect(0, 340, 411, 401))
        self.meibi_log.setStyleSheet("QTextEdit {\n"
"    background-color: #000000;\n"
"    border: 1px solid #1a1a1a;\n"
"    color: #ffffff;\n"
"    font-family: \'Consolas\', \'Monospace\';\n"
"    font-size: 10pt;\n"
"}")
        self.meibi_log.setReadOnly(True)
        self.meibi_log.setObjectName("meibi_log")
        self.MeibiChatInput = QtWidgets.QLineEdit(parent=self.Meibi)
        self.MeibiChatInput.setGeometry(QtCore.QRect(0, 740, 411, 22))
        self.MeibiChatInput.setStyleSheet("QLineEdit {\n"
"    background-color: #000000;\n"
"    border: 1px solid #1a1a1a;\n"
"    color: #ffffff;\n"
"    font-family: \'Consolas\', \'Monospace\';\n"
"    font-size: 10pt;\n"
"}")
        self.MeibiChatInput.setObjectName("MeibiChatInput")
        self.meibi_log.raise_()
        self.Label_2.raise_()
        self.Face_2.raise_()
        self.MeibiChatInput.raise_()
        self.Hana = QtWidgets.QFrame(parent=self.centralwidget)
        self.Hana.setGeometry(QtCore.QRect(0, 0, 411, 761))
        self.Hana.setStyleSheet("")
        self.Hana.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Hana.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Hana.setObjectName("Hana")
        self.Label = QtWidgets.QLabel(parent=self.Hana)
        self.Label.setGeometry(QtCore.QRect(0, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(24)
        font.setBold(True)
        self.Label.setFont(font)
        self.Label.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    padding: 5px;\n"
"    background-color: #000000;\n"
"}")
        self.Label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Label.setLineWidth(2)
        self.Label.setMidLineWidth(1)
        self.Label.setObjectName("Label")
        self.hana_log = QtWidgets.QTextEdit(parent=self.Hana)
        self.hana_log.setGeometry(QtCore.QRect(0, 340, 411, 401))
        self.hana_log.setStyleSheet("QTextEdit {\n"
"    background-color: #000000;\n"
"    border: 1px solid #1a1a1a;\n"
"    color: #ffffff;\n"
"    font-family: \'Consolas\', \'Monospace\';\n"
"    font-size: 10pt;\n"
"}")
        self.hana_log.setReadOnly(True)
        self.hana_log.setObjectName("hana_log")
        self.Face = QtWidgets.QLabel(parent=self.Hana)
        self.Face.setGeometry(QtCore.QRect(0, 50, 191, 291))
        self.Face.setText("")
        self.Face.setPixmap(QtGui.QPixmap("C:\\Users\\User\\helloworld\\build\\helloworld\\android\\gradle\\app\\src\\main\\assets\\assets/hana_faces/5.png"))
        self.Face.setScaledContents(True)
        self.Face.setWordWrap(False)
        self.Face.setObjectName("Face")
        self.HanaChatInput = QtWidgets.QLineEdit(parent=self.Hana)
        self.HanaChatInput.setGeometry(QtCore.QRect(2, 740, 411, 22))
        self.HanaChatInput.setStyleSheet("QLineEdit {\n"
"    background-color: #000000;\n"
"    border: 1px solid #1a1a1a;\n"
"    color: #ffffff;\n"
"    font-family: \'Consolas\', \'Monospace\';\n"
"    font-size: 10pt;\n"
"}")
        self.HanaChatInput.setObjectName("HanaChatInput")
        self.hana_log.raise_()
        self.Label.raise_()
        self.Face.raise_()
        self.HanaChatInput.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mirai-Ko Hana"))
        self.Ver.setText(_translate("MainWindow", "Mirai-Ko Hana v0.1"))
        self.HVer.setText(_translate("MainWindow", "Hana-OS v0.5.1"))
        self.MVer.setText(_translate("MainWindow", "Hana2-OS v-1.0.0"))
        self.UploadBtn.setText(_translate("MainWindow", "Stage Image"))
        self.Label_2.setText(_translate("MainWindow", "Hana"))
        self.meibi_log.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Consolas\',\'Monospace\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Label.setText(_translate("MainWindow", "Hana"))


if __name__ == "__main__":
    import sys
    from PyQt6 import QtWidgets
    import mirai_ko_girls

    app = QtWidgets.QApplication(sys.argv)
    
    # This forces the app to load your actual logic and button events
    window = mirai_ko_girls.MainWindow()
    
    window.show()
    sys.exit(app.exec())